
steps:
  - name: tofu-plan
    image: alpine:latest
    backend_options:
      docker:
        extra_hosts:
          - "host:host-gateway"
    environment:
      TF_VAR_homelab_ip:
        from_secret: TF_VAR_homelab_ip
      TF_VAR_minio_root_password:
        from_secret: TF_VAR_minio_root_password
      TF_VAR_tf_state_bucket_name:
        from_secret: TF_VAR_tf_state_bucket_name
      TF_VAR_domain_base:
        from_secret: TF_VAR_domain_base
      TF_VAR_vps_ip:
        from_secret: TF_VAR_vps_ip
      TF_VAR_cloudflare_api_token:
        from_secret: TF_VAR_cloudflare_api_token
      TF_VAR_cloudflare_account_id:
        from_secret: TF_VAR_cloudflare_account_id
      TF_VAR_cloudflare_zone_id:
        from_secret: TF_VAR_cloudflare_zone_id
      TF_VAR_docker_registry_admin_password:
        from_secret: TF_VAR_docker_registry_admin_password
      TF_VAR_woodpecker_agent_secret:
        from_secret: TF_VAR_woodpecker_agent_secret
      TF_VAR_github_client_id:
        from_secret: TF_VAR_github_client_id
      TF_VAR_github_client_secret:
        from_secret: TF_VAR_github_client_secret
      TF_VAR_woodpecker_admin_user:
        from_secret: TF_VAR_woodpecker_admin_user
      SSH_KEY:
        from_secret: ssh_key
    commands:
      - sh scripts/setup-ssh.sh
      - sh scripts/install-tofu.sh
      - cd stages/infra
      - tofu init
      - tofu plan -out=tfplan
  
  - name: approve-plan
    image: registry.liberato.dev/plugin-gatekeeper:latest
    depends_on:
      - tofu-plan
    settings:
      driver: github
      server: https://api.github.com
      token:
        from_secret: TF_VAR_github_client_secret
      approvers:
        - Liberontissauri
      timeout: 30m

  - name: tofu-apply
    image: alpine:latest
    backend_options:
      docker:
        extra_hosts:
          - "host:host-gateway"
    environment:
      TF_VAR_homelab_ip:
        from_secret: TF_VAR_homelab_ip
      TF_VAR_minio_root_password:
        from_secret: TF_VAR_minio_root_password
      TF_VAR_tf_state_bucket_name:
        from_secret: TF_VAR_tf_state_bucket_name
      TF_VAR_domain_base:
        from_secret: TF_VAR_domain_base
      TF_VAR_vps_ip:
        from_secret: TF_VAR_vps_ip
      TF_VAR_cloudflare_api_token:
        from_secret: TF_VAR_cloudflare_api_token
      TF_VAR_cloudflare_account_id:
        from_secret: TF_VAR_cloudflare_account_id
      TF_VAR_cloudflare_zone_id:
        from_secret: TF_VAR_cloudflare_zone_id
      TF_VAR_docker_registry_admin_password:
        from_secret: TF_VAR_docker_registry_admin_password
      TF_VAR_woodpecker_agent_secret:
        from_secret: TF_VAR_woodpecker_agent_secret
      TF_VAR_github_client_id:
        from_secret: TF_VAR_github_client_id
      TF_VAR_github_client_secret:
        from_secret: TF_VAR_github_client_secret
      TF_VAR_woodpecker_admin_user:
        from_secret: TF_VAR_woodpecker_admin_user
      SSH_KEY:
        from_secret: ssh_key
    depends_on:
      - approve-plan
    commands:
      - sh scripts/setup-ssh.sh
      - sh scripts/install-tofu.sh
      - cd stages/infra
      - tofu apply tfplan 