
steps:
  - name: tofu-plan
    image: alpine:latest  # or debian, ubuntu, etc.
    backend_options:
      docker:
        extra_hosts:
          - "host:host-gateway"
    environment:
      TF_VAR_homelab_ip:
        from_secret: TF_VAR_homelab_ip
      TF_VAR_minio_root_password:
        from_secret: TF_VAR_minio_root_password
      TF_VAR_tf_state_bucket_name:
        from_secret: TF_VAR_tf_state_bucket_name
      TF_VAR_domain_base:
        from_secret: TF_VAR_domain_base
      TF_VAR_vps_ip:
        from_secret: TF_VAR_vps_ip
      TF_VAR_cloudflare_api_token:
        from_secret: TF_VAR_cloudflare_api_token
      TF_VAR_cloudflare_account_id:
        from_secret: TF_VAR_cloudflare_account_id
      TF_VAR_cloudflare_zone_id:
        from_secret: TF_VAR_cloudflare_zone_id
      TF_VAR_docker_registry_admin_password:
        from_secret: TF_VAR_docker_registry_admin_password
      TF_VAR_woodpecker_agent_secret:
        from_secret: TF_VAR_woodpecker_agent_secret
      TF_VAR_github_client_id:
        from_secret: TF_VAR_github_client_id
      TF_VAR_github_client_secret:
        from_secret: TF_VAR_github_client_secret
      TF_VAR_woodpecker_admin_user:
        from_secret: TF_VAR_woodpecker_admin_user
      SSH_KEY:
        from_secret: ssh_key
    commands:
      # Setup SSH key
      - mkdir -p ~/.ssh
      - echo "$SSH_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - apk add --no-cache openssh-client
      - ssh-keyscan -H $TF_VAR_homelab_ip >> ~/.ssh/known_hosts
      - ssh-keyscan -H $TF_VAR_vps_ip >> ~/.ssh/known_hosts
      # Debug: Print connection info
      - echo "=== SSH Key Info ==="
      - ls -la ~/.ssh/
      - echo "SSH key first line:" && head -n 1 ~/.ssh/id_rsa
      - echo "SSH_KEY env var is set:" && test -n "$SSH_KEY" && echo "YES" || echo "NO"
      - echo "SSH_KEY env var length:" && echo "$SSH_KEY" | wc -c
      - echo "SSH key file matches env var:" && echo "$SSH_KEY" | diff - ~/.ssh/id_rsa && echo "MATCH" || echo "MISMATCH"
      - echo "=== Known Hosts ==="
      - cat ~/.ssh/known_hosts
      - echo "=== Environment Variables ==="
      - echo "Homelab IP:" $TF_VAR_homelab_ip
      - echo "VPS IP:" $TF_VAR_vps_ip
      - echo "=== Network Connectivity ==="
      - apk add --no-cache netcat-openbsd curl
      - echo "Testing homelab SSH port..."
      - nc -zv $TF_VAR_homelab_ip 22 || echo "Homelab SSH port unreachable"
      - echo "Testing VPS SSH port..."
      - nc -zv $TF_VAR_vps_ip 22 || echo "VPS SSH port unreachable"
      - echo "Testing homelab ping..."
      - ping -c 3 $TF_VAR_homelab_ip || echo "Homelab unreachable"
      - echo "Testing VPS ping..."
      - ping -c 3 $TF_VAR_vps_ip || echo "VPS unreachable"
      - echo "=== DNS Resolution ==="
      - nslookup $TF_VAR_homelab_ip || echo "DNS resolution failed for homelab"
      - nslookup $TF_VAR_vps_ip || echo "DNS resolution failed for VPS"
      - echo "=== Test SSH Connection ==="
      - ssh -v -o StrictHostKeyChecking=no -o ConnectTimeout=10 root@$TF_VAR_homelab_ip "echo 'Homelab SSH OK'" || echo "Homelab SSH failed"
      - ssh -v -o StrictHostKeyChecking=no -o ConnectTimeout=10 root@$TF_VAR_vps_ip "echo 'VPS SSH OK'" || echo "VPS SSH failed"
      # Install OpenTofu
      - apk add --no-cache curl cosign gpg  # for Alpine
      - |
        curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh
        chmod +x install-opentofu.sh
        ./install-opentofu.sh --install-method standalone
      # Run your plan
      - cd stages/infra
      - tofu init
      - tofu plan