
steps:
  - name: tofu-plan
    image: alpine:latest  # or debian, ubuntu, etc.
    backend_options:
      docker:
        extra_hosts:
          - "host:host-gateway"
    environment:
      TF_VAR_homelab_ip:
        from_secret: TF_VAR_homelab_ip
      TF_VAR_minio_root_password:
        from_secret: TF_VAR_minio_root_password
      TF_VAR_tf_state_bucket_name:
        from_secret: TF_VAR_tf_state_bucket_name
      TF_VAR_domain_base:
        from_secret: TF_VAR_domain_base
      TF_VAR_vps_ip:
        from_secret: TF_VAR_vps_ip
      TF_VAR_cloudflare_api_token:
        from_secret: TF_VAR_cloudflare_api_token
      TF_VAR_cloudflare_account_id:
        from_secret: TF_VAR_cloudflare_account_id
      TF_VAR_cloudflare_zone_id:
        from_secret: TF_VAR_cloudflare_zone_id
      TF_VAR_docker_registry_admin_password:
        from_secret: TF_VAR_docker_registry_admin_password
      TF_VAR_woodpecker_agent_secret:
        from_secret: TF_VAR_woodpecker_agent_secret
      TF_VAR_github_client_id:
        from_secret: TF_VAR_github_client_id
      TF_VAR_github_client_secret:
        from_secret: TF_VAR_github_client_secret
      TF_VAR_woodpecker_admin_user:
        from_secret: TF_VAR_woodpecker_admin_user
      SSH_KEY:
        from_secret: ssh_key
    commands:
      # Setup SSH key
      - mkdir -p ~/.ssh
      - echo "$SSH_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - apk add --no-cache openssh-client
      - ssh-keyscan -H $TF_VAR_homelab_ip >> ~/.ssh/known_hosts
      - ssh-keyscan -H $TF_VAR_vps_ip >> ~/.ssh/known_hosts
      # Install OpenTofu
      - apk add --no-cache curl cosign gpg  # for Alpine
      - |
        curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh
        chmod +x install-opentofu.sh
        ./install-opentofu.sh --install-method standalone
      # Run your plan
      - cd stages/infra
      - tofu init
      - tofu plan -out=tfplan

  - name: tofu-apply
    image: alpine:latest  # or debian, ubuntu, etc.
    backend_options:
      docker:
        extra_hosts:
          - "host:host-gateway"
    environment:
      TF_VAR_homelab_ip:
        from_secret: TF_VAR_homelab_ip
      TF_VAR_minio_root_password:
        from_secret: TF_VAR_minio_root_password
      TF_VAR_tf_state_bucket_name:
        from_secret: TF_VAR_tf_state_bucket_name
      TF_VAR_domain_base:
        from_secret: TF_VAR_domain_base
      TF_VAR_vps_ip:
        from_secret: TF_VAR_vps_ip
      TF_VAR_cloudflare_api_token:
        from_secret: TF_VAR_cloudflare_api_token
      TF_VAR_cloudflare_account_id:
        from_secret: TF_VAR_cloudflare_account_id
      TF_VAR_cloudflare_zone_id:
        from_secret: TF_VAR_cloudflare_zone_id
      TF_VAR_docker_registry_admin_password:
        from_secret: TF_VAR_docker_registry_admin_password
      TF_VAR_woodpecker_agent_secret:
        from_secret: TF_VAR_woodpecker_agent_secret
      TF_VAR_github_client_id:
        from_secret: TF_VAR_github_client_id
      TF_VAR_github_client_secret:
        from_secret: TF_VAR_github_client_secret
      TF_VAR_woodpecker_admin_user:
        from_secret: TF_VAR_woodpecker_admin_user
      SSH_KEY:
        from_secret: ssh_key
    commands:
      # Setup SSH key
      - mkdir -p ~/.ssh
      - echo "$SSH_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keyscan -H $TF_VAR_homelab_ip >> ~/.ssh/known_hosts
      - ssh-keyscan -H $TF_VAR_vps_ip >> ~/.ssh/known_hosts
      # Install OpenTofu
      - apk add --no-cache curl cosign gpg  # for Alpine
      - |
        curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh
        chmod +x install-opentofu.sh
        ./install-opentofu.sh --install-method standalone
      # Run your apply
      - cd stages/infra
      - tofu apply tfplan 
    when:
      event:
        - deployment