
steps:
  - name: tofu-plan
    image: alpine:latest  # or debian, ubuntu, etc.
    backend_options:
      docker:
        extra_hosts:
          - "host:host-gateway"
    commands:
      # Install OpenTofu
      - apk add --no-cache curl cosign gpg  # for Alpine
      - |
        curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh
        chmod +x install-opentofu.sh
        ./install-opentofu.sh --install-method standalone
      # Run your plan
      - cd stages/infra
      - tofu init
      - tofu plan